### ISSUE TITLE
Simplifying the content creation process

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#489]
## Overview
The current content creation process is very restrictive, and sets out a standard format/flow for the flashcards -- that is a user must set objectives, content and a test. These are also required, meaning you cannot create a course without having each of these components.
To simplify the content flow, we will need to remove this current flow ( objectives, content and a test) and just have a content tab, where the objectives and test cards are just set as a card types.
A user will be able to use any card type (quiz and content) in any order they choose. We also need to remove the requirements for adding a duration

## Conditions of satisfaction
* When entering a lesson, users no longer see the three activity links: objective, content, and test knowledge. Instead, when entering a lesson, users see a new start card showing lesson details
* Pagination starts with the first card and includes all cards until the end of the test.
* Remove success/completion screens that currently exist at the end of “objectives” and “content” sections.
* A content manager can add any card in any order on the CMS (objective, content and test)
* Remove required fields for, 
  * Title on objectives, content and test.
  * Content duration

**Comment by pedro16v** [comment]
Hi @andrewwapling. Regarding the simplification of the content creation process, can you please help clarify if this is the correct sequence?

1. From the first card users would tap "Continue" or a Lesson. 
2. Users would see a first Lesson card with initial details.
3. Users see the first card and can continue to the next cards.

**If the above is correct, my question is:**
For the second card below, what text is fixed and what is editable? Or is the text always fixed except for the variables `lesson name` and `course title`?
- [ ] Ready to go
- [ ] You're about to commence `lesson name here`
- [ ] This lesson covers a range of useful information aimed at extending your knowledge base in `course title`


Course detail | Lesson/Activity detail | Lesson/Activity first card
---|---|---
<img width="325" alt="Screenshot 2021-03-11 at 14 43 40" src="https://user-images.githubusercontent.com/2813677/110741708-76750900-8278-11eb-82a0-0c9a35a7bafc.png"> | <img width="324" alt="Screenshot 2021-03-11 at 14 42 45" src="https://user-images.githubusercontent.com/2813677/110741717-7d9c1700-8278-11eb-827e-55dac3088ee4.png"> | <img width="325" alt="Screenshot 2021-03-11 at 14 47 17" src="https://user-images.githubusercontent.com/2813677/110741863-ba680e00-8278-11eb-84dd-cd6f8c395d44.png">

**Comment by megganeturner** [comment]
Hi! A couple of questions for the front-end implementation here:

1. I just want to clarify that we're completely removing the 'lesson module complete' sections? The issue says yes, but it still appears in [the invision](https://projects.invisionapp.com/d/main/#/console/20251865/435851465/preview#project_console) (this excludes the feedback card, which will still be displayed at the end of the lesson)
2. If a user has started a lesson and then closed it, should we present them the option to continue?
2a. If we do not present an option to continue, should there be a limit (in wagtail) for how many cards can be added to a lesson? For example, if a lesson contained 40 cards and a user exited at 20, it wouldn't be a great experience to have to start again

**Comment by pedro16v** [comment]
Thanks for raising these up!

1. I seem to remember that the decision was the remove those completion cards. Maybe @andrewwapling can help here?
2. Good point. We do have a "Continue" button but no mechanism to pick from actually continuing or starting from the beginning. I think it's equally annoying if I want to restart but I previously left it at card 40/80 and now I have to tap back 39 times :grin: I'll see who can clarify this.

**Comment by pedro16v** [comment]
So, we have a "Continue" button on the Course Detail screen.

I _assume_ these are correct (are they?)

1. On an unvisited Course, tapping Continue opens Lesson 1.
2. On a Course with multiple lessons, the first lesson has been completed. Tapping Continue opens Lesson 2.

And what about these?

* User has completed Lesson 1 and started Lesson 2 but exited before finishing. Later, the user is back to the Course Detail screen and taps Continue. What happens?
  1. Opens Lesson 2 on the first card
  2. Opens Lesson 2 where the user left it. (But what if I want to restart the lesson (too long ago / don't remember / my nephew was fooling around with the app)
  3. Opens Lesson 3

**Comment by PeteCoward** [comment]
1. yes, to my understanding, no more section/module complete spashes
2. In a lesson, we only know if a lesson is complete or not now ( not how many cards they got into it ).

This means we as of now always go in at the start. If this needs to be improved it needs to be discussed and prioritised separately

**Comment by andrewwapling** [comment]
Hi @pedro16v @megganeturner @PeteCoward , 

1. Yes this activity section confirmation screen has been defactored. I've removed this from the core design prototype
2. Yes we should offer a continue function for users to aid in ease of completion. This ties in with the intuitive user experience approach of play, pause and continue that we've introduced in the course detail. Currently the design offers a number of different 'continue' incentives for users to jump back into previously started courses and lessons:
    2a. 'Start / Continue' CTA button on the home screen in the hero banner at top of screen: https://invis.io/M4Z81IYT3J6
    2b. 'Continue Learning' featured cards listing on the home screen: https://invis.io/M4Z81IYT3J6
    2c. 'Continue Learning' featured cards listing on the course category listing screen: https://invis.io/SG103958ZTAW
    2d. 'Continue' CTA flag chevron on the course cards on the course category listing screen: https://invis.io/SG103958ZTAW
    2e. 'Start / Continue' CTA button on the course detail screen in the intro area at top of screen: https://invis.io/RC10E9E6US2K
    2f. 'Continue' CTA flag chevron on the lesson cards on the course detail screen: https://invis.io/RC10E9E6US2K
    
    Hope this helps and drop me a line with any queries at all.
    
    Thanks again, Andy
